---
title: "Pokemon"
author: "Kiernan"
editor: visual
---

```{r}
#| echo: false
#| warning: false

library(readr)
library(gtsummary)
library(dplyr)
```

```{r}
#| echo: false
#| message: false
#| include: false

# column names
poke_cols <- c("id", "pokemon", "species_id", "height", "weight",
							 "base_experience", "type_1", "type_2", "hp", "attack", "defense",
							 "special_attack", "special_defense", "speed", "color_1", "color_2", "color_f",   
							 "egg_group_1", "egg_group_2", "url_icon", "generation_id", "url_image")

# read in raw data, replacing missing values with NA
pokemon <- read_csv(here::here("Data", "2025", "2025-04-01", "pokemon_df.csv"),
				 na = "-1",
				 skip= 1, col_names = poke_cols)
```

```{r}
#| echo: false
#| label: tbl-one
#| tbl-cap: "Descriptive Statisitcs"
 
# getting the median and IQR for hp, attack, defense, special attack, special defense, and sped stats based
# on the primary typing for each Pokemon.

tbl_summary(
  pokemon,
  by = type_1,
  include = c(hp, attack, defense, special_attack, special_defense, speed)
)

unique_pokemon_forms <- nrow(pokemon)
```
@tbl-one shows base stats stratified by primary typing. There were `r unique_pokemon_forms` Pokemon (including all forms and variants)

```{r}
#| echo: false
#| label: tbl-two
#| tbl-cap: Linear Regression

# Linear regression predicting weight based on base stats

linear_model <- lm(weight ~ hp + attack + defense + special_attack + special_defense + speed, data = pokemon)

gtsummary::tbl_regression(
  linear_model,
  label = list(
    special_attack ~ "special attack",
    special_defense ~ "special defense"
  ),
  intercept = TRUE,
)
```
@tbl-two uses hp, attack, defense, special attack, special defense, and speed stats to predict the weight of a Pokemon

```{r}
#| echo: false

# Function that takes a Pokemon name and calculates its base stat total
bst <- function(pokemon_name, data = pokemon) {
  
  data <- dplyr::mutate(data, name_lower = tolower(pokemon))
  pokemon_name_lower <- tolower(pokemon_name)
  rows <- dplyr::filter(data, name_lower %in% pokemon_name_lower)

  
 if (nrow(rows) == 0) {
    return(paste(pokemon_name, "not found."))
  }
  

  rows <- rows[match(pokemon_name_lower, rows$name_lower), ]
  
  base_stat_total <- rows$hp + rows$attack + rows$defense +
                     rows$special_attack + rows$special_defense + rows$speed
  
  return(base_stat_total) 
}  
  
```

```{r}
# Function Test

bst("infernape")
bst(c("slaking", "charizard", "Dialga", "ding-dong"))
bst("ding-dong")
```

```{r}
#| echo: false
#| label: fig-one
#| fig-cap: "Distribution of Base Stat Totals"

# Making a histogram showing the distribution of Pokemon base stat totals

hist(bst(pokemon$pokemon), main = "Base Stat Total Distribution", xlab = "Base Stat Totals")

```
@fig-one shows the distribution of Pokemon base stat totals
